name = "DataSandbox"
uuid = "3b089fd0-d4f4-49d0-9aef-16b71bcc8397"
authors = ["John Jackson", "University of Colorado Boulder"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
